### ISSUE TITLE
What about handling side-effects outside?

### ISSUE THREAD

**Issue by lmatteis** [jaystack/repatch#11]
Many approaches in Redux for handling side-effects and async code, do it outside the loop, by listening for specific actions and dispatching others accordingly. Notable examples are Redux-saga or Redux-observable.

Without an actual action type constant, this doesn't seem possible to achieve in repatch.

**Comment by jayhasyee** [comment]
I can say many things related to this issue.

1) Repatch also has `thunk` middleware. With this you can handle side-effects via `extraArgument`.

2) Repatch also has middleware interface, those compose up the `dispatch` method . So you can create a middleware, which handles objects as actions. This way you can resolve any redux-specific middleware.

3) In the 2) case Repatch would be very similar to Redux. But the purpose is not there. Actually middlewares in Repatch do not make sense. The dispatched reducers are not serialisable entities. So analysing them could not be the Jedi way. The most of middleware functionality should be listeners on the store, like redux-persist. But I would like to provide a convenient way to handle side-effects before reducing without middlewares. I am considering this to a new major version.

**Comment by jayhasyee** [comment]
I close this issue, because it does not bind tasks in the repository yet.
The next major version will ship a more repatch-like approximation to handling third-party side-effects.
