### ISSUE TITLE
What about an action that affects multiple stores ?

### ISSUE THREAD

**Issue by shivekkhurana** [jaystack/repatch#12]
Hi Péter, 

The verbosity of redux is painful at times and your solution seems brilliant. 

![](https://media.giphy.com/media/eIqt0Yd3vgfXG/giphy.gif)

But I'm not able to get my head around how to trigger actions that affect multiple stores. 

Ex: 
Assume two stores:

**Auth Store**
Saves session_token, session_start_time and session_valid_until_time

**User Store**
Saves the logged_in_user (name, email, avatar etc)

The auth api returns auth data as well user data when /login is successful. Hence, in the standard redux universe, there is an action called login:
```js
export function login(username, password) {
  api.post('/login', {username, password}).then(res => {
    return (dispatch) => { //thunk
        dispatch({type: 'userLoginSuccess', payload: res});
    };
  })
}
```

Then the user store and auth store will have a case listening for 'userLoginSuccess' action type and will return a derivative of the state with required mutations. 

As Repatch actions returns mutations to it's stores, can we achieve this One(action)-to-Many(reducers) flow in Repatch ?

Thanks 
K

**Comment by jayhasyee** [comment]
Dear Shivek,

First thank you for join repatch users.

What do you mean *two stores*? Redux recommends that you should maintain only one store, your singletone state of your application. If you have two store instances, you need to maintain two thunk middlewares too. So in this case your redux action won't trigger both of them, unless you dispatch your action multiple times.

I assume you mean two sub-states in the sole store, eg.:

```
{
  auth: {
    sessionToken,
    sessionStartTime,
    sessionValidUntilTime
  },
  user: {
    name,
    email,
    avatar
  }
}
```

In this case in Redux you should define two sub-reducers, and both of them listening to one action.

In Repatch terminology actions are missing. So you can't interpret to listening them.

```javascript
export function login(username, password) {
  return _ => async (dispatch, getState, { api } ) => {
    const {
      sessionToken,
      sessionStartTime,
      sessionValidUntilTime,
      user
    } = await api.post('/login', { username, password });
    dispatch(state => ({
      ...state,
      auth: {
        sessionToken,
        sessionStartTime,
        sessionValidUntilTime
      },
      user
    }));
  }
}
```

Repatch interprets sub-reducers differently. You find it [here](https://www.npmjs.com/package/repatch#sub-reducers). If your reducible data is deeply nested, you can use these helpers.

I hope I answered your question well.

**Comment by shivekkhurana** [comment]
@jayhasyee 
Yup. You answered it to perfection. `npm installing repatch` for my next project !

Thanks you.
