### ISSUE TITLE
how do you time travel debugging?

### ISSUE THREAD

**Issue by jiyinyiyong** [jaystack/repatch#13]
Normally with actions we have the benefits of recording all actions and replay them like time traveling. I did that too in my own implementation of [store](https://github.com/Respo/reel/blob/master/src/reel/core.cljs#L20). Since they are functions, how do you deal with time traveling?

**Comment by jayhasyee** [comment]
First of all, let me explain, how redux time travelling works. As you mentioned we need to store all `actions`, the `initialState` and the `reducer` of course. Then to reproduce any state during the application life:

```js
const travelTo = (index = Infinity) => actions.slice(0, index).reduce(reducer, initialState)
```

Repatch does not forbid time traveling, even though its actions are not serialisable. On every change of the store you can create a *patch*, which is a deep difference between two consecutive states. Then by storing patches, we can reduce to any intermediate state during the application life:

```js
const createPatch = (prevState, state) => ...
const applyPatch = (prevState, patch) => ...

const createTimeMachine = store => {
  const patches = []
  const initialState = store.getState()
  let prevState = initialState
  store.subscribe(() => {
    const state = store.getState()
    patches.push(createPatch(prevState, state))
    prevState = state
  })
  return {
    travelTo: (index = Infinity) => store.state =  patches.slice(0, index).reduce(applyPatch, initialState)
  }
}
```

**Comment by jayhasyee** [comment]
IMHO: I can recommend the [deep-diff](https://www.npmjs.com/package/deep-diff) package to creating patches. By the way we are considering a repatch-devtool similar to redux-devtool.

**Comment by jiyinyiyong** [comment]
Thanks for replying. It's an interesting idea. I digged into immutable-diff before. I consider diffing bare JavaScript objects would be slower compared to immutable data. But it's still a nice idea.

**Comment by jayhasyee** [comment]
@jiyinyiyong Yes, it has some performance overhead, but it is still optional in dev mode, if you use this time-travelling. But, redux pattern is always creating action objects by the action creators, which have permanent performance overhead. This overhead is missing in repatch.
That's a balance: **conservation of the work**. But this work is still optional here :)

**Comment by jiyinyiyong** [comment]
Actually I don't use time traveling often, especially in projects without immutable data. Sometimes I just consider time traveling as a proof of theory that everything fits into React's patterns well, pure rendering, single source of trues, repeatability(or should I say predictability...). Yeah we have to take care of trade-offs in real world projects.
