### ISSUE TITLE
Using with react-redux

### ISSUE THREAD

**Issue by dbryand** [jaystack/repatch#14]
I'm trying to use repatch with react-redux as described in the docs, but I cannot get past the redux dependency that react-redux has here:

![image](https://user-images.githubusercontent.com/9218/34228656-6bbf4850-e59f-11e7-97af-631e8bb426cf.png)

Is the expectation that we would also have to install redux?

Thanks!

**Comment by hasyee** [comment]
Unfortunately `react-redux` needs `redux` for some reason. When I published `repatch` this was not the case.

**Comment by dbryand** [comment]
Thanks--do you see another way to effectively use Repatch with React in a large app?

**Comment by hasyee** [comment]
I don't know about this. Possible way is to create a `react-repatch` lib, but that would be the same in each line, because both of `redux` and `repatch` has almost the same interface :) `react-redux` is a very simple and lightweight lib, which perfectly performs this connection.
