### ISSUE TITLE
This repo stopped development?

### ISSUE THREAD

**Issue by vongohren** [jaystack/repatch#15]

**Comment by isthisstackoverflow** [comment]
Afaik there's simply no open issues/TODOs at the moment.

**Comment by vongohren** [comment]
I agree, but still 4-6 months since last commit. Things happen fast in this world :P

**Comment by hasyee** [comment]
Dear @vongohren,
Repatch is a very simple library with less than 100 lines of code, so the issues are really sparse. Therefore the constantly developing isn't necessary right now. Even though behind of Repatch is a great team (JayStack), and we won't let this repo. We can always keep in touch via Github, if you have any issue. :)

**Comment by vongohren** [comment]
Thank you for quick response, it proves the livelyness of the repo. So closing this now!
