### ISSUE TITLE
<Provider> does not support changing `store` on the fly.

### ISSUE THREAD

**Issue by severisv** [jaystack/repatch#16]
Hey, first of all thanks for a great library!

I have a question:

When using with `react-redux` and hot reloading, this warning pops up in the console:
```
<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions.
```

I'm not sure if this has a practical implication, or it's just the warning, but in the link they suggest you do 
```
 if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextRootReducer = require('../reducers/index');
      store.replaceReducer(nextRootReducer);
    });
  }
```
which of course is not possible in repatch.

Is it anything to worry about, or should I just disable the warning?
(And if you know, how can I disable the warning?)

Cheers!

**Comment by hasyee** [comment]
Hey,
you guess right, it does not make sense. In Repatch the actions are also the reducers on their own, so the store remains unchanged during the application hot-reloading phases, therefore you can ignore this warning.
Does it drop this warning even in production?

**Comment by severisv** [comment]
No, only when using hot-reloading so it won't show up in production, and also I think react-redux doesn't log much if `NODE_ENV` is production

**Comment by isthisstackoverflow** [comment]
What does your entry file look like? I use repatch with the HotModuleReplacementPlugin and do not get such a warning.

I have this at the end of my App.js, so maybe these are the magic lines.

```
if (module.hot) {
    module.hot.accept();
}
```

**Comment by severisv** [comment]
This is my entry point:
```
const store = createStore(initialState);

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById("root")
);


// Hot Module Replacement
if (module.hot) {
  module.hot.accept();
}

```

I'm using parcel with the built-in HMR. Maybe there's a difference

**Comment by isthisstackoverflow** [comment]
I have the Provider in a separate ProviderWrapper that's where your Provider is. That ProviderWrapper looks like

```
<Provider store={createStore(initialState)}>
  <MoreProviders>
    {props.children}
...
```

No idea why this would change anything, though, just guessing what it could be.
