### ISSUE TITLE
works with redux logger?

### ISSUE THREAD

**Issue by crdil** [jaystack/repatch#2]
First thank you for sharing this package and making it easier and less verbose to implement state management. I wonder if it's possible to use redux-logger with repatch? I've tried to add redux-logger as middleware without success. 

```javascript
import Store, { thunk } from 'repatch';
import { logger } from 'redux-logger';

export default new Store({
  counter: 0,
})
  .addMiddleware(thunk)
  .addMiddleware(logger);
```

Am I doing something wrong or is repatch not compatible with redux-logger?

If it's not compatible, is there anyway I can access the name of the called action in the middleware?

**Comment by jayhasyee** [comment]
It is not compatible. Redux works a quite differently then repatch. For example redux middlewares take actions as second argument, but in repatch there are no actions.
I linked the related section in the api reference, where I implemented a very simple logger:
https://github.com/jaystack/repatch/blob/master/docs/store.md#addmiddlewaremiddlewares
Some enhancement could be that we take the deep difference between the previous and current state, like in redux-devtools.
As soon as possible I would like to provide a useful logger middleware in this package, but it is not difficult to implement yourself ;)
