### ISSUE TITLE
What about reducer only returning part of state that changed (and merging)?

### ISSUE THREAD

**Issue by mostr** [jaystack/repatch#6]
Hey,

First of all, congrats for the project! I like the idea of eliminating redux verbosity and boilerplate which always bothers me a bit. One question though: as far as I can see currently the functions return complete new state. Have you thought about returning only part of state that changes and merging it with previous state afterwards? Like this:

Say current state is as follows:
``` json
{
  "todos": [],
  "isFetching": false,
  "showCompleted": false
}
```

Now the action/reducer fn could be (in some cases) written as
``` javascript
const setFetchInProgress = () => state => ({isFetching: true});
// instead of
const setFetchInProgress = () => state => ({...state, isFetching: true});
```

And then `dispatch` could be:
``` typescript
dispatch: Dispatch<R> = reducer => {
    if (typeof reducer !== 'function') {
      throw new Error('Reducer is not a function: dispatch takes only reducers as functions.');
    }
    this.state = {...this.state, ...reducer(this.state)};
    this.listeners.forEach(listener => listener());
    return <R>reducer;
};
```

This has one drawback I can think of, namely that state ***must be*** an object, not a primitive (e.g. number as in counter example), but this is not an issue for real world projects I guess.

It's just the Idea and if it's fine I can contribute a PR with that change.

**Comment by jayhasyee** [comment]
@mostr first welcome to the repatch users :)
Your idea is similar to React's `setState` mechanism. Indeed, that would make developing more convenient, but I wouldn't like to restrict what reducers can do. Eg. the reducer should change the whole state, or delete some properties from that:

```javascript
const removeUnnecessaryIsFetching = () => state => {
  const nextState = { ...state }
  delete nextState.isFetching
  return nextState
}
```

And that is not exactly the same as

```javascript
const removeUnnecessaryIsFetching = () => state =>  ({ isFetching: undefined })
```

I would like to keep repatch as simple as I can and avoid restrictions.

However you can create a helper:

```javascript
const merge = reducerSlice => state => ({ ...state, ...reducerSlice(state) })
```

and use it:

```javascript
const setFetchInProgress =

**Comment by jayhasyee** [comment]
Or you can create a middleware:

```javascript
const merger = store => next => reducer => next(state => ({ ...state, ...reducer(state) }))
```

```javascript
const store = new Store(...).addMiddleware(merger)
```
